# create expanded_dict.csv
import re
import pandas as pd
import csv
import os
import re
import global_options as gl
import json 

# list of list input
list_of_lists = [['cash_flow', 'revenue', 'growth', 'increase', 'balance_sheet', 'quarter', 'adjust_ebitda', 'free_cash', 'cash', 'strong', 'continue', 'income', 'net', 'investment', 'financial', 'gross_margin', 'business', 'debt', 'sale', 'grow'],
['gross_margin', 'margin', 'lease', 'pipeline', 'mobile_game', 'rent', 'hotel', 'tenant', 'gross_profit', 'competitive_landscape', 'leasing_spread', 'business', 'growth', 'revenue', 'public_cloud', 'strong', 'cloud', 'leasing', 'long_term', 'continue'],
['income', 'increase', 'revenue', 'adjust_ebitda', 'net', 'cash_flow', 'loan', 'quarter', 'compare', 'gaap', 'growth', 'balance_sheet', 'expense', 'decrease', 'gross_profit', 'total', 'investment', 'continue', 'cash', 'strong','revenue', 'profit', 'gross_profit', 'income', 'profitability', 'net', 'client', 'percentage', 'profitable', 'gross', 'recur', 'user', 'contribution', 'monetization', 'recognition', 'percent', 'recognize', 'quarter', 'subscription', 'statement'],
['dividend', 'dividend_policy', 'share_repurchase', 'buyback', 'special_dividend', 'dividend_payout', 'payout_ratio', 'shareholder', 'repurchase', 'stock_buyback', 'interim_dividend', 'cash', 'stock', 'free_cash', 'cash_flow', 'share', 'equity', 'buyback_authorization', 'capital', 'ordinary_dividend', 'combine_ratio', 'payout_ratio', 'ratio', 'loss', 'underlie', 'motor', 'attritional_loss', 'claim', 'nat_cat', 'underwriting', 'short_tail', 'solvency_ratio', 'reserve', 'cat', 'target', 'accident', 'cat_loss', 'normalize', 'corrective_measure', 'claim_frequency'],
['growth', 'organic', 'top_line', 'grow', 'volume', 'rate', 'increase', 'expansion', 'accelerate', 'trend', 'revenue', 'strong', 'acceleration', 'slow', 'half', 'quarter', 'slowdown', 'imply', 'sequential', 'flat','double_digit', 'single_digit', 'mid_single', 'double_digits', 'digit', 'growth', 'triple_digit', 'low', 'grow', 'high', 'single_digits', 'mid', 'digits', 'mid_upper', 'comp', 'range', 'revenue', 'business', 'strong', 'rate'],
['quarter', 'fourth', 'guidance', 'expect', 'expectation', 'fiscal', 'range', 'utilization', 'calendar', 'half', 'month', 'time_frame', 'flat', 'run', 'estimate', 'projection', 'impact', 'forecast', 'guess', 'quarterly'],
['capex', 'capital', 'investment', 'asset', 'capital_expenditure', 'fund', 'capital_allocation', 'diversification', 'cap', 'portfolio', 'noncore_asset', 'diversify', 'invest', 'capitalize', 'return', 'wealth_management', 'disposition', 'reit', 'divest', 'liquidity'],
['tax', 'effective_tax', 'taxis', 'defer_tax', 'tax_reform', 'rate', 'deferred_tax', 'taxable_income', 'cash', 'valuation_allowance', 'income', 'loss_carryforward', 'tax_shield', 'discrete_item', 'deduction', 'tax_refund', 'pay', 'credit', 'tax_exempt', 'bonus_depreciation'],
['expense', 'cost', 'fee', 'operating', 'overhead', 'corporate_overhead', 'professional_fee', 'saving', 'administrative_expense', 'noninterest_expense', 'expenditure', 'legal', 'charge', 'corporate', 'incur', 'spend', 'reduction', 'onetime', 'relate', 'branch_closure'],
['market', 'share', 'penetration', 'competitor', 'gain', 'competitive', 'position', 'competition', 'presence', 'growth', 'player', 'grow', 'price', 'addressable', 'emerge', 'size', 'guess', 'business', 'lose', 'penetrate'],
['balance_sheet', 'cash_flow', 'cash', 'debt', 'free_cash', 'equity', 'liquidity', 'balance', 'capital', 'burn', 'leverage', 'refinance', 'flow', 'financing', 'bond', 'asset', 'restricted_cash', 'payment', 'pay', 'fund','pro_forma', 'basis', 'acquisition', 'revenue', 'growth', 'ebitda', 'organic', 'combine', 'forma', 'exclude', 'leverage', 'include', 'pro', 'math', 'dobank', 'adjustment', 'report', 'annualize', 'tutor', 'transaction'],
['debt', 'loan', 'borrowing', 'bad_debt', 'refinance', 'rate', 'bond', 'sensitivity', 'financing', 'mortgage', 'net', 'debt_repayment', 'borrower', 'repayment', 'borrow', 'repay', 'lending', 'bank', 'pay', 'ebitda'],
['impairment', 'impairment_charge', 'depreciation', 'depreciation_amortization', 'goodwill', 'charge_off', 'amortization', 'goodwill_impairment', 'amortization_intangible', 'purchase_accounting', 'contingent_consideration', 'write_off', 'write_down', 'intangible_asset', 'asset', 'write_goodwill', 'charge', 'write', 'disposal', 'accounting'],
['customer', 'churn', 'client', 'service_provider', 'service', 'subscriber', 'exist', 'retention', 'business', 'base', 'enterprise', 'large', 'subscription', 'relationship', 'platform', 'cloud', 'quality', 'grow', 'add', 'product','cohort', 'customer', 'old_cohort', 'cohort_cohort', 'client', 'demographic', 'segment', 'enrollment', 'segmentation', 'sample_size', 'concentration', 'user', 'analysis', 'consumer', 'marketing', 'metric', 'profile', 'large', 'hyper_scale', 'beta'],
['inventory', 'shift_gear', 'switch_gear', 'booking', 'inventory_correction', 'shifting_gear', 'channel', 'switching_gear', 'dealer', 'helpful_switching', 'distributor', 'destocke', 'level', 'destocking', 'aged_inventory', 'quarter', 'stock', 'inventory_buildup', 'shipment', 'restock'],
['cross_sell', 'mix', 'cross_selling', 'portfolio', 'product', 'shift', 'change', 'blend', 'margin', 'price', 'vary_depend', 'sale', 'sell', 'effect', 'line', 'diversify', 'overlap', 'sort', 'client', 'vary'],
['currency', 'foreign_exchange', 'foreign_currency', 'constant_currency', 'local_currency', 'canadian_dollar', 'exchange', 'dollar', 'australian_dollar', 'euro', 'british_pound', 'translation_effect', 'translation', 'impact', 'currency_translation', 'forex', 'yen', 'hedge', 'exposure', 'swiss_franc'],
['launch', 'product', 'release', 'platform', 'development', 'road_map', 'evolve', 'time_frame', 'roadmap', 'evolution', 'generation', 'innovation', 'feature', 'update', 'version', 'timeline', 'adoption', 'design', 'announcement', 'technology'],
['utilization', 'capacity', 'capacity_constraint', 'facility', 'spare_capacity', 'plant', 'nameplate_capacity', 'production', 'horsepower', 'unused_capacity', 'efficiency', 'resource', 'megawatt', 'add', 'idle', 'manufacturing', 'storage', 'run', 'bottleneck', 'utilize'],
['litigation', 'court', 'appeal', 'legal', 'settlement', 'lawsuit', 'case', 'arbitration', 'judge', 'patent', 'law', 'trial', 'claim', 'preliminary_injunction', 'file', 'appeal_court', 'decision', 'injunction', 'lawyer', 'process'],
['geography', 'region', 'country', 'regional', 'geographic', 'geographic_region', 'geographic_expansion', 'expansion', 'location', 'geographic_footprint', 'territory', 'north_american', 'geographical', 'expand', 'market', 'geographie', 'global', 'cross_border', 'area', 'local'],
['seasonality', 'normal_seasonality', 'typical_seasonality', 'seasonal', 'seasonal_pattern', 'normal_seasonal', 'outlook', 'quarter', 'typical_seasonal', 'strong', 'fourth', 'pattern', 'seasonal_uptick', 'sequential', 'business', 'half', 'weak', 'season', 'expect', 'seasonal_slowdown'],
['pricing', 'price', 'increase', 'dynamic', 'pressure', 'demand', 'inflation', 'environment', 'premium', 'volume', 'stable', 'change', 'market', 'competition', 'lag', 'competitive', 'raise', 'hike', 'tiere_pricing', 'tio'],
['joint_venture', 'partnership', 'partner', 'collaboration', 'partnering', 'relationship', 'agreement', 'alliance', 'jv_partner', 'cooperation', 'strategic', 'collaborate', 'joint', 'venture', 'affiliation_agreement', 'arrangement', 'exclusive', 'announce', 'strategic_alliance', 'work', 'confidentiality_agreement', 'disclose', 'disclosure', 'confidential', 'confidentiality', 'liberty_disclose', 'information', 'agreement', 'contractual_obligation', 'confidential_information', 'contract', 'public', 'definitive_agreement', 'detailed', 'materiality', 'allow', 'specific', 'teacher', 'haven', 'transaction'],
['leverage', 'margin', 'valuation', 'price', 'pricing', 'pressure', 'guess', 'range', 'operate', 'lever', 'power', 'energy', 'ratio', 'comfortable', 'cost', 'dollar', 'elasticity', 'target', 'ability', 'volume'],
['backlog', 'order', 'book', 'cancellation', 'shipment', 'ship', 'delivery', 'contract', 'cancel', 'booking', 'deliver', 'unannounced_order', 'delay', 'incoming_order', 'sort', 'visibility', 'wait', 'month', 'receive', 'reorder', 'jump_queue', 'back_queue', 'hop_queue', 'queue', 'great', 'hop', 'participant', 'helpful', 'quick', 'color', 'final', 'guy', 'revenue', 'operator', 'competitive_landscape', 'previous_questioner', 'update', 'growth', 'kind', 'electronic_monitoring', 'order_intake', 'order', 'intake', 'backlog', 'book_bill', 'unannounced_order', 'strong', 'prepayment', 'passive_safety', 'project', 'book', 'ramp_up', 'quarter', 'automotive', 'top_line', 'growth', 'dual_fuel', 'downpayment', 'weak', 'half', 'book_bill', 'tangible_book', 'booking', 'backlog', 'book', 'order', 'dilution', 'ratio', 'quarter', 'award', 'trail_month', 'strong', 'revenue', 'convertible_prefer', 'convertible_preferred', 'conditional', 'aerospace_defense', 'electronics', 'electronic', 'recompete'],
['discount', 'rebate', 'incentive', 'concession', 'coupon', 'price', 'incentive_comp', 'pricing', 'renegotiation', 'reduction', 'promotional', 'incentive_compensation', 'premium', 'rebate_rebate', 'promotion', 'policy', 'renegotiate', 'sale', 'fair', 'fee'],
['efficiency', 'productivity', 'improvement', 'operational_efficiency', 'performance', 'throughput', 'upgrade', 'improve', 'operational', 'continuous_improvement', 'fine_tuning', 'update', 'execution', 'process', 'ratio', 'run', 'operation', 'benefit', 'operating', 'increase'],
['raw_material', 'commodity_price', 'cost', 'commodity', 'input', 'price', 'resin', 'material', 'inflation', 'canadian_dollar', 'steel', 'raw_mat', 'metal', 'synthetic_rubber', 'pricing', 'import', 'oil', 'pressure', 'aluminum', 'increase'],
['weather', 'cold_weather', 'rain', 'storm', 'winter_weather', 'winter', 'snow', 'weather_pattern', 'hurricane', 'flood', 'warm_weather', 'rainy_season', 'weather_condition', 'polar_vortex', 'snowfall', 'severe_weather', 'mild_winter', 'drought', 'winter_storm', 'ice_storm'],
['store', 'online', 'sale', 'retail', 'mall_traffic', 'commerce', 'traffic', 'productivity', 'mall', 'retailer', 'salesperson', 'comp', 'performance', 'rep', 'salespeople', 'website', 'internet', 'digital', 'marketplace', 'brick_mortar'],
['cost', 'acquisition', 'fee', 'customer', 'cogs', 'subscriber', 'chip', 'manufacturing', 'integration', 'charge', 'production', 'marketing', 'price', 'commission', 'purchase', 'shipping', 'service', 'pay', 'product', 'acquire'],
['regulatory', 'regulation', 'compliance', 'permit', 'regulator', 'regulatory_framework', 'regulatory_requirement', 'regulatory_compliance', 'approval', 'government', 'regulatory_approval', 'inspection', 'restriction', 'regulate', 'environmental_permit', 'rule', 'policy', 'law', 'issue', 'environment'],
['automation', 'robotic', 'labor', 'cost', 'cost_cutting', 'industrial_automation', 'reduction', 'efficiency', 'robotic_automation', 'machine', 'robot', 'automate', 'software', 'technology', 'productivity', 'work', 'factory_automation', 'optimization', 'reduce', 'saving'],
['bundle', 'advanced_packaging', 'packaging', 'pricing', 'price', 'bundle_bundle', 'cable', 'package', 'discount', 'product', 'cable_operator', 'pack', 'bundled', 'pack_pack', 'offer', 'unbundle', 'triple_play', 'multiple', 'solution', 'quad_play'],
['supply_chain', 'supplier', 'shipment', 'distribution', 'supply', 'shipping', 'freight', 'delivery', 'procurement', 'ship', 'vendor', 'supply_constraint', 'export', 'center', 'efficiency', 'network', 'packaging', 'logistic', 'module_shipment', 'import','want_circle', 'logistical', 'opt', 'dual', 'entice', 'pent_demand', 'weld', 'pen_demand', 'rezone', 'ebb_flow', 'constraint', 'presume', 'extrapolate', 'refinery', 'muddy', 'discontinuous', 'silver', 'nickel', 'shifting', 'gallon'],
['inflation', 'economy', 'loan', 'monetary_policy', 'turkish_lira', 'growth', 'income', 'economic', 'bank', 'banking', 'capital_adequacy', 'increase', 'investment', 'unemployment', 'gdp', 'foreign_currency', 'central_bank', 'sector', 'currency', 'country','macro_environment', 'macro'],
['hire', 'turnover', 'talent', 'retention', 'recruiting', 'recruit', 'recruitment', 'hiring', 'attrition', 'churn', 'employee', 'staff', 'training', 'recruit_talent', 'retain_talent', 'people', 'leave', 'skill_set', 'recruiter', 'skill'],
['patent', 'intellectual_property', 'license', 'patent_expire', 'licensing', 'patent_patent', 'litigation', 'licensing_agreement', 'patent_infringement', 'patent_litigation', 'patent_expiration', 'lawsuit', 'patent_protection', 'infringe_patent', 'file', 'patent_expiry', 'patent_lawsuit', 'transfer', 'royalty', 'trade_secret'],
['reinsurance', 'insurance', 'life_insurance', 'insurance_reinsurance', 'reinsurer', 'mortality', 'premium', 'cat', 'underwriting', 'cede_commission', 'interruption_insurance', 'loss', 'property_casualty', 'risk', 'disability', 'quota', 'mortality_morbidity', 'cede_premium', 'claim', 'insurer'],
['restructuring_charge', 'restructuring', 'restructure', 'change', 'reorganization', 'organizational_structure', 'structure', 'structural', 'realignment', 'hasn_change', 'corporate', 'organization', 'charge', 'org_structure', 'replace', 'corporate_headquarters', 'organizational', 'remain_unchanged', 'business', 'strategy'],
['brand', 'brand_awareness', 'consumer', 'innovation', 'convergent_offer', 'luxury', 'guest', 'branding', 'fashion', 'launch', 'marketing_campaign', 'strong', 'campaign', 'portfolio', 'share', 'social_medium', 'marketing', 'market', 'category', 'product','advertising', 'marketing', 'marketing_campaign', 'advertising_campaign', 'campaign', 'advertiser', 'political_advertising', 'tv', 'election', 'spend', 'promotion', 'national', 'efficiency', 'advertisement', 'brand', 'national_advertiser', 'roi', 'ad', 'billboard', 'effectiveness'],
['forecast', 'industry', 'forecasting', 'sector', 'projection', 'industrial', 'predict', 'metric', 'market', 'outlook', 'prediction', 'vertical_integration', 'small_diameter', 'unorganized_sector', 'price', 'demand', 'forecaster', 'economy', 'benchmark', 'expectation'],
['headcount', 'quota_carry', 'head_head', 'head', 'employee', 'head_office', 'staff', 'hire', 'quota_carrier', 'people', 'rep', 'quota', 'reduction', 'count', 'salary', 'personnel', 'worker', 'quota_bear', 'voluntary_involuntary', 'workforce'],
['segment', 'division', 'breakdown', 'split', 'break', 'unit', 'divisional', 'rough_breakdown', 'report', 'operation', 'reporting', 'segmentation', 'separate', 'cut', 'operating', 'reportable_segment', 'unallocated', 'business', 'divide', 'breakup'],
['risk', 'safety', 'operational', 'reliability', 'threat', 'compliance', 'uncertainty', 'project', 'issue', 'management', 'security', 'operation', 'regulator', 'control', 'execution', 'safe', 'business', 'manage', 'process', 'failure'],
['category', 'mix', 'product', 'segment', 'big_chunk', 'line', 'gross_margin', 'performance', 'split', 'margin', 'assortment', 'item', 'break', 'quad_core', 'piece', 'mixture', 'segmentation', 'give_color', 'sku', 'component'],
['machine_learn', 'cloud', 'security', 'technology', 'solution', 'artificial_intelligence', 'iot', 'application', 'device', 'attack', 'machine_learning', 'network', 'platform', 'enterprise', 'video', 'deep_learning', 'public_cloud', 'user', 'enable', 'software'],
['headwind', 'headwind_tailwind', 'tailwind', 'revenue', 'offset', 'quarter', 'half', 'neutral', 'face', 'guess', 'site_selection', 'comp', 'expect', 'quantify', 'guidance', 'growth', 'wind', 'fourth', 'plus_minuse', 'sound'],
['datum_center', 'infrastructure', 'data_analytic', 'data_center', 'capability', 'cloud', 'analytic', 'network', 'datum', 'data', 'platform', 'technology', 'upgrade', 'server', 'intelligence', 'capex', 'application', 'analytical_capability', 'storage', 'predictive_analytic'],
['board_meeting', 'board', 'board_member', 'independent_director', 'corporate_governance', 'shareholder', 'board_approve', 'director', 'special_committee', 'board_authorize', 'governance', 'decision', 'committee', 'role', 'committee_meeting', 'director_director', 'independent', 'member', 'appoint', 'meeting'],
['funding', 'research_development', 'innovation', 'development', 'project', 'spend', 'fund', 'cost', 'spending', 'technology', 'research', 'investment', 'expenditure', 'budget', 'money', 'capitalize', 'technological_innovation', 'nuclear_waste', 'dollar', 'effort'],
['subsidiary', 'affiliate', 'own_subsidiary', 'entity', 'separate_entity', 'standalone_entity', 'overseas_subsidiary', 'manager_affiliate', 'parent', 'equity', 'ultimate_outcome', 'company', 'profit_sharing', 'combined_entity', 'loss', 'profit', 'affiliation', 'joint_venture', 'legal_entity', 'separate'],
['severance', 'termination_fee', 'severance_charge', 'cost', 'expense', 'payment', 'charge', 'termination', 'saving', 'employee', 'onetime', 'personnel', 'incur', 'restructure', 'relate', 'bonus', 'restructuring', 'quarter', 'pay', 'cash','minimum_wage', 'wage_inflation', 'wage', 'labor', 'inflation', 'wage_hike', 'hourly_wage', 'salary', 'employee', 'salary_wage', 'pressure', 'increase', 'worker_compensation', 'casual_dining', 'tip', 'pay', 'hour', 'cost', 'state', 'payroll'],
['deposit', 'reserve', 'deposit_beta', 'deposit_gathering', 'release', 'interest_bear', 'cd', 'campaign', 'funding', 'hike', 'depositor', 'rate', 'broker', 'growth', 'strengthen', 'rise', 'stabilization', 'stable', 'borrowing', 'municipality'],
['carbon', 'renewable_energy', 'biomass', 'energy', 'electricity', 'air_pollution', 'nuclear_power', 'emission', 'power_plant', 'natural_gas', 'renewable', 'sustainability', 'pellet_plant', 'environmental', 'climate', 'fuel_cell', 'greenhouse_gas', 'terawatt_hour', 'carbon_emission', 'fossil_fuel'],
['fiber', 'laser', 'flash_array', 'flash', 'power', 'laser_diode', 'fiber_tower', 'technology', 'fan', 'application', 'welding', 'dark_fiber', 'cutting', 'printer', 'ink', 'diode', 'network', 'fiber_optic', 'advanced_packaging', 'vectore'],
['ceo_search', 'permanent_ceo', 'ceo', 'interim_ceo', 'leadership', 'role', 'transition', 'candidate', 'search', 'executive', 'executive_search', 'senior', 'appointment', 'successor', 'resign', 'senior_leadership', 'search_permanent', 'president', 'executive_team', 'manager', 'retirement', 'congratulation', 'pleasure', 'congrat', 'wish_retirement', 'luck', 'career', 'pende', 'sad', 'congratulate_promotion', 'retire', 'enjoy', 'congratulation_appointment', 'retire_retire', 'phenomenal_job', 'upward_revision', 'adventure', 'working', 'miss', 'geographic_breakdown'],
['loyalty_program', 'gift_card', 'loyalty', 'credit_card', 'member', 'program', 'loyalty_reward', 'reward', 'card', 'loyal', 'guest', 'marketing', 'customer', 'reward_loyalty', 'gift', 'promotional_activity', 'offer', 'mobile_app', 'send_message', 'consumer','customer_satisfaction', 'score', 'guest_satisfaction', 'feedback', 'happy', 'satisfaction', 'smile_face', 'customer', 'rating', 'client', 'consumer_behavior', 'content', 'quality', 'survey', 'satisfaction_score', 'smile', 'compliment'],
['long_term', 'strategic', 'opportunity', 'strategy', 'goal', 'leverage', 'target', 'short', 'opportunity_arise', 'medium', 'bright', 'future', 'ambition', 'baseband', 'focus', 'plan', 'horizon', 'objective', 'long', 'stakeholder'],
['hedge', 'hedging', 'natural_hedge', 'policy', 'unhedged', 'strategy', 'lock', 'collar', 'price', 'volatility', 'oil', 'layer', 'hedged', 'natural_hedging', 'exposure', 'month', 'place', 'protect_downside', 'rolling', 'euro_pound'],
['korean', 'russian', 'subscriber', 'dividend_payout', 'game', 'nuclear_power', 'tariff', 'user', 'data_usage', 'handset', 'sticker', 'coal_fire', 'power_plant', 'profit', 'refining', 'payout_ratio', 'dividend', 'revenue', 'advertisement', 'contact_department','chinese', 'sovereign_exposure', 'chinese_government', 'sovereign', 'sovereign_wealth', 'country', 'risk_weight', 'european', 'usual_suspect', 'western_european', 'bond', 'eurasian', 'sovereign_sovereign', 'government', 'foreign', 'nationality', 'geopolitical', 'irish', 'risk', 'bank'],
['feel_confident', 'feel_comfortable', 'confident', 'feel', 'feel_uncomfortable', 'confidence', 'naysayer', 'comfortable', 'guidance', 'handicapping', 'manufacturable', 'degree_confidence', 'tone_tenor', 'claw', 'flawless', 'wrong_impression', 'convey_message', 'stop_bleed', 'division_president', 'dub'],
['pension', 'pension_fund', 'pension_deficit', 'pension_liability', 'pension_scheme', 'deficit', 'lump_sum', 'pension_trustee', 'liability', 'trustee', 'obligation', 'scheme', 'contribution', 'discount', 'surplus', 'payment', 'rate', 'cash', 'funding', 'solvency'],
['security', 'cyber_security', 'secure', 'protection', 'unknown_threat', 'defense', 'cybersecurity', 'secure_unsecured', 'attack', 'sensitive_information', 'confidential_information', 'protect', 'immune_system', 'unsecured', 'threat', 'information', 'cyber', 'surveillance', 'screen_protection', 'parental_control'],
['credit', 'credit_card', 'credit_facility', 'credit_rating', 'loan', 'downgrade', 'risk', 'quality', 'debit_card', 'portfolio', 'fico_score', 'nonaccrual', 'provision', 'credit_scoring', 'rating', 'loss', 'deterioration', 'composite_score', 'credit_union', 'benign','rating_agency', 'grade_rating', 'rating', 'credit_rating', 'debt', 'detailed_review', 'rating_downgrade', 'conversation', 'agency', 'geographic_diversification', 'investment', 'grade', 'discussion', 'leverage', 'constructive_conversation', 'alleviate_concern', 'equity', 'contact', 'unrated', 'hybrid'],
['stress_test', 'risk_weight', 'stress_testing', 'stress_scenario', 'stress', 'risk_weighting', 'asset', 'bank', 'probability_default', 'scenario', 'loan', 'adverse_scenario', 'financial_crisis', 'capital', 'mortgage', 'ccar', 'portfolio', 'risk', 'regulator', 'loss'],
['yield', 'accretable_yield', 'portfolio', 'duration', 'security', 'yield_curve', 'single_family', 'investment', 'bond', 'reinvestment', 'equity', 'enhancement', 'average', 'origination', 'bps', 'retail_nonretail', 'flattening_yield', 'proppant_loading', 'reinvest_proceed', 'accretable'],
['milestone_payment', 'milestone', 'royalty', 'payment', 'upfront_payment', 'receive', 'trigger', 'approval', 'equal_installment', 'upcoming_milestone', 'initiation', 'recognize', 'regulatory_approval', 'collaboration', 'receipt', 'revenue', 'eligible', 'lump_sum', 'pivotal_trial', 'late_stage'],
['diversity', 'community', 'culture', 'social', 'school', 'african_american', 'community_college', 'worker', 'cultural', 'student', 'hispanic', 'people', 'donation', 'violence', 'workforce', 'political', 'curriculum', 'distinctive_feature', 'child_age', 'visual'],
['maintenance_outage', 'maintenance_shutdown', 'maintenance', 'outage', 'shutdown', 'maintenance_downtime', 'outage_outage', 'routine_maintenance', 'repair_maintenance', 'shutdown_shutdown', 'schedule', 'unplanne_outage', 'maintenance_repair', 'turnaround', 'plan', 'downtime', 'shut', 'nitrate', 'mill_mill', 'material_handling'],
['base_compensation', 'incentive_comp', 'incentive_compensation', 'bonus_accrual', 'stock', 'incentive_accrual', 'incentive', 'accrual', 'compensation', 'stock_compensation', 'variable_compensation', 'bonus', 'accrue', 'expense', 'quarter', 'reversal', 'fourth', 'noncash', 'share', 'comp'],
['diluted_share', 'dilute_share', 'count', 'basic_diluted', 'share', 'diluted', 'basic_dilute', 'outstanding', 'dilute', 'dilution', 'convertible', 'diluted_weighted', 'diluted_earning', 'basic', 'convert', 'found_member', 'ish_ish', 'couple_quickie', 'earn_out', 'average'],
['synergy', 'merger', 'acquisition', 'consolidation', 'integration', 'acquire', 'opportunity', 'consolidate', 'synergy_realization', 'company', 'deal', 'cost', 'merge', 'synergie', 'transaction', 'business', 'strategic', 'target', 'potential'],
['election', 'political_uncertainty', 'government', 'political', 'political_situation', 'federal_government', 'presidential_election', 'uncertainty', 'politician', 'vote_vote', 'state', 'bipartisan_support', 'governor', 'politic', 'delegate', 'election_election', 'risk', 'midterm_election', 'federal', 'vote'],
['expire', 'shelf_life', 'expiration', 'life', 'longevity', 'expiry', 'mortality', 'lifetime', 'contract', 'longevity_swap', 'renewal', 'agreement', 'expire_expire', 'unrealized_loss', 'negotiation', 'wine', 'option', 'life_expectancy', 'renew', 'fullness_time'],
['covenant', 'compliance_covenant', 'covenant_covenant', 'breach_covenant', 'revolving_credit', 'covenant_breach', 'facility', 'amendment', 'waiver', 'quid_pro', 'amend_extended', 'file_tomorrow', 'bank', 'amend', 'cautionary', 'compliance', 'foregone_conclusion', 'cure', 'agreement', 'plenty_room'],
['sale_force', 'arrow_quiver', 'hire', 'spit', 'size', 'top_performer', 'sale_reps', 'people', 'graph', 'rep', 'sale', 'pain', 'sell', 'body', 'regrow', 'brigatinib', 'lloyd', 'decorate', 'usher', 'add'],
['engagement', 'passion_dedication', 'employee', 'team', 'dedication', 'wonderful_job', 'terrific_job', 'loyalty', 'happy', 'veteran', 'servant', 'worth_pointing', 'dedication_hard', 'successful', 'finality', 'culture', 'join_tonight', 'shareholder', 'colleague', 'echo_sentiment'],
['coverage_ratio', 'coverage', 'distribution', 'write_off', 'inflow_outflow', 'idr', 'cover', 'advisement', 'provision', 'npl', 'resumption', 'target', 'gabe', 'comfortable', 'max', 'coup', 'writing', 'matured', 'long_term', 'growth'],
['warrant', 'warrant_exercise', 'warrant_warrant', 'exercise_warrant', 'fair_warrant', 'exercise', 'strike', 'outstanding', 'stock', 'public_filing', 'reverse_split', 'disappear', 'denominator_calculation', 'exercisable', 'share', 'trading', 'prospectus_file', 'price', 'rep_warranty', 'raise'],
['exercise_option', 'option_exercise', 'option', 'exercise', 'deadline', 'nondisclosure_agreement', 'expire', 'american', 'mr', 'push_button', 'jet', 'obligate', 'restrict_stock', 'grandfathere', 'agreement', 'anchor', 'date', 'upsize', 'notice', 'boralex'],
['small_cell', 'carrier', 'indoor', 'macro', 'fiber', 'tower', 'densification', 'deployment', 'wireless_carrier', 'antenna', 'site', 'outdoor', 'cell', 'anchor_tenant', 'deploy', 'tenancy', 'network', 'dark_fiber', 'tone_conversation', 'backhaul'],
['hear_rumor', 'rumor', 'rumor_speculation', 'speculation_rumor', 'comment', 'rhapsody', 'policy', 'speculation', 'pure_speculation', 'speculative', 'stadium', 'explore_option', 'marketplace', 'festival', 'false', 'writer', 'veracity', 'refute', 'contradict', 'unfortunate'],
['flu_season', 'flu', 'season', 'influenza', 'infectious_disease', 'disease', 'strain', 'circulate', 'knock_wood', 'health_care', 'alere', 'outbreak', 'death', 'weather_pattern', 'seasonal_influenza', 'hotspot', 'severe', 'mortality', 'acuity', 'vaccine'],
['apple_apple', 'comparison', 'apple_comparison', 'symbol', 'compare', 'direct_mail', 'variance', 'machining', 'discretion', 'apple_orange', 'variant', 'relinquish', 'flippant', 'og', 'slide_deck', 'comparable', 'benign', 'mid_single', 'exclude', 'gem'],
['crystal_ball', 'digestion', 'contracting', 'ball', 'push_envelope', 'dive', 'crystal_clear', 'lag', 'upstream', 'baccarat', 'tipping_point', 'museum', 'gaze', 'rig_count', 'fed', 'repayment', 'cathy', 'murky', 'inflection_point', 'duncan','difficult_predict', 'impossible_predict', 'soft_landing', 'predict', 'appraiser', 'buyer', 'rebuilding', 'unwavere_commitment', 'inspection_inspection', 'toll_road', 'addition_subtraction', 'warning_letter', 'hearten', 'prediction', 'rough_idea', 'judgment', 'builder', 'bankrupt', 'wildcard', 'fast'],
['zinc', 'copper_zinc', 'buoyancy', 'copper_concentrate', 'deficit', 'price', 'smelter', 'skeptic', 'concentrate', 'sufficient_liquidity', 'hidden', 'precious_metal', 'premium', 'output', 'production', 'ore_body', 'copper', 'ore', 'expansion', 'lead'],
['auction', 'bidding', 'bid', 'participate', 'megahertz_auction', 'nugget', 'bauxite', 'consignment', 'bidder', 'selective', 'rwe', 'forthcoming', 'qualify', 'conduct', 'activity', 'farming', 'santander', 'goalpost', 'gigahertz', 'tricky'],
['drill', 'iron_ore', 'drilling', 'open_pit', 'well_drill', 'drill_well', 'drill_hole', 'grade', 'meter', 'ore', 'ore_body', 'mine_life', 'zone', 'exploration', 'resource', 'life_mine', 'mineralization', 'mining', 'gold', 'grade_gram','big_picture', 'ole', 'film', 'tv_panel', 'movie', 'oled', 'box_office', 'film_slate', 'panel', 'sized_panel', 'quantum_dot', 'ole_display', 'tv', 'title', 'display', 'panel_maker', 'blackout_period', 'long_term', 'guess', 'technology', 'big_picture', 'ole', 'film', 'tv_panel', 'movie', 'oled', 'box_office', 'film_slate', 'panel', 'sized_panel', 'quantum_dot', 'ole_display', 'tv', 'title', 'display', 'panel_maker', 'blackout_period', 'long_term', 'guess', 'technology','revolver', 'draw_revolver', 'ammunition', 'firearm_ammunition', 'firearm', 'gun', 'ammo', 'handgun', 'hunt', 'availability_revolver', 'caliber', 'cash', 'category', 'draw', 'demand', 'shotgun', 'pay', 'liquidity', 'shelf_space', 'covenant','sailing_season', 'vessel', 'charter', 'weak_canadian', 'tonnage', 'general_administrative', 'canadian_dollar', 'fiscal', 'ship', 'fleet', 'ago_period', 'boat', 'shuttle_tanker', 'vessel_vessel', 'decrease', 'constant_currency', 'old_vessel', 'detailed_explanation', 'iron_ore', 'barrel_day', 'barrel_oil', 'barrel', 'production', 'ethane_rejection', 'water_injection', 'produce', 'rubiale', 'water_river', 'field', 'capacity', 'ethane_recovery', 'oil', 'plateau', 'gathering_system', 'equivalent', 'alkylate', 'ethane', 'crude', 'capable_handle', 'permian', 'permian_basin', 'basin', 'crude', 'shale_play', 'spread_widen', 'completion', 'horizontal', 'condensate', 'gathering_system', 'oil', 'takeaway', 'gravity', 'drill', 'delineation', 'basin_basin', 'rig', 'area', 'onshore_offshore', 'differential', 'polysilicon', 'silicon_metal', 'ethylene', 'polyethylene', 'wafer', 'metric_ton', 'poly', 'silicone', 'polypropylene', 'poly_wafer', 'price', 'silicon', 'propylene', 'thin_film', 'demand', 'fbr', 'solar', 'high_purity', 'polymer', 'raw_material', 'autonomous_driving', 'autonomous_vehicle', 'autonomous', 'auto', 'light_vehicle', 'robot', 'deep_learning', 'automation', 'car', 'autonomous_car', 'automotive', 'vehicle', 'robotic', 'automaker', 'home_automation', 'automate', 'semi_autonomous', 'motor_controller', 'mapping', 'automate_driving', 'lithium', 'cement', 'battery', 'price', 'tantalum', 'grade', 'volume', 'brine', 'demand', 'increase', 'acid', 'supply', 'extract', 'ton', 'arbitration', 'plant', 'apple_orange', 'middle_budgeting', 'cement_aggregate', 'import', 'fuel_surcharge', 'fuel', 'surcharge', 'diesel', 'fare', 'currency_neutral', 'rodney', 'tow', 'shape_form', 'fritz', 'exuberant', 'freight', 'price', 'tedious', 'leaf', 'currency', 'correlate', 'airfare']]

headers = ['Cash Flows', 'Profit Margin', 'Revenue', 'Dividend', 'Growth', 'Short Term Guidance', 'Investment', 'Corporate Tax', 'Operating Cost', 'Market Share', 'Financial Position', 'Financing', 'Asset Impairment', 'Customer Segment Analysis', 'Inventory Turnover', 'Sales Pipeline', 'Foreign Exchange Impact', 'New Product Launches', 'Capacity Utilization', 'Litigation Risk', 'Geographic Expansion', 'Seasonality', 'Pricing Power', 'Partnerships And Collaborations', 'Debt-To-Equity Ratio', 'Backlog or order book status', 'Promotion Strategy', 'Productivity Metrics', 'Raw Material', 'Weather', 'Online Sales', 'Customer Acquisition Costs', 'Regulation', 'Productivity', 'Bundle Pricing Strategies', 'Supply Chain', 'Macroeconomics', 'Talent Hiring', 'Corporate Innovation', 'Insurance', 'Organization Restructuring', 'Marketing Strategy', 'Industry Forecast', 'Employee Headcount', 'Business Segment Breakdowns', 'Operational Risk', 'Product Performance', 'Artificial Intelligence', 'Challenges', 'Cloud Computing', 'Corporate Governance', 'Research and Development', 'Subsidiary Performance', 'Labor Costs', 'Funding Rate', 'Environmental', 'Firm Specific', 'CEO Transition', 'Customer Management', 'Business Strategy', 'Risk Hedging', 'Geopolitical Risk', 'Confident', 'Pension', 'Cybersecurity', 'Credit Rating', 'Regulation Risk', 'Financing Cost', 'Payment (Sales And Marketing)', 'Social Responsibility', 'Machinery Outage', 'Compensation', 'Diluted Shares', 'Merger & Acquisition', 'Political Risk', 'Expiration', 'Loan Covenant', 'Sales Force Productivity', 'Employee Engagement', 'Liquidity Risk', 'Warrant Exercise', 'Option Exercise', 'IT Infrastructure Investment', 'Rumor', 'Flu Season', 'Industry benchmarking', 'Economic Forecast', 'Commodity', 'Auction', 'Industry Specific']


# Convert each list string into a Python list
# for lst in list_of_list:
#     # Split the string into individual words
#     words = list(set(lst))
#     list_of_lists.append(words)
def create_expanded_dict():
    # Your header string
    # Ensure the number of headers matches the number of lists
    assert len(headers) == len(list_of_lists), "Number of headers and lists do not match."
    # print(len(headers))
    # print(len(list_of_lists))

    # Find the maximum length among all lists
    max_length = max(len(lst) for lst in list_of_lists)
    output_filename = os.path.join(gl.OUTPUT_FOLDER, "dict", "expanded_dict.csv")
    # Open a CSV file for writing
    with open('expanded_dict.csv', 'w', newline='', encoding='utf-8') as csvfile:
        csvwriter = csv.writer(csvfile)
        # Write the header
        csvwriter.writerow(headers)
        # Write the rows
        for i in range(max_length):
            row = []
            for lst in list_of_lists:
                if i < len(lst):
                    row.append(lst[i])
                else:
                    row.append('')
            csvwriter.writerow(row)
            

def create_seed_dict():
    # Your header string
    # Ensure the number of headers matches the number of lists
    assert len(headers) == len(list_of_lists), "Number of headers and lists do not match."

    # Create a dictionary from headers and list_of_lists
    expanded_dict = {headers[i]: list_of_lists[i] for i in range(len(headers))}

    output_filename = os.path.join(gl.OUTPUT_FOLDER, "dict", "seed_dict.json")
    # Write the dictionary to a JSON file
    with open(output_filename, 'w', encoding='utf-8') as jsonfile:
        json.dump(expanded_dict, jsonfile, ensure_ascii=False, indent=4)


if __name__ == "__main__":
    # create_expanded_dict()
    create_seed_dict()